package pdo.deepspace;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import pdo.deepspace.DP;

import pdo.deepspace.DPDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dPDaoConfig;

    private final DPDao dPDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dPDaoConfig = daoConfigMap.get(DPDao.class).clone();
        dPDaoConfig.initIdentityScope(type);

        dPDao = new DPDao(dPDaoConfig, this);

        registerDao(DP.class, dPDao);
    }
    
    public void clear() {
        dPDaoConfig.getIdentityScope().clear();
    }

    public DPDao getDPDao() {
        return dPDao;
    }

}
